version: '3.8'

services:
  postgres:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-doom_password}  # Используем переменную окружения

  doom-bot:
    restart: unless-stopped
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
    volumes:
      - ./media:/app/media:rw  # Только чтение для безопасности
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25' 
